imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

m6_web_kafka:
    event_dispatcher: true
    producers:
       eventUsers:
           configuration:
               metadata.broker.list: '127.0.0.1'
           brokers:
               - '127.0.0.1'
               - '10.05.05.19'
           log_level: 3
           topics:
               eventUsers:
                   configuration:
                       auto.commit.interval.ms: 1000
                   strategy_partition: 2

    consumers:
        eventUsers:
            configuration:
                metadata.broker.list: '127.0.0.1'
                group.id: 'example'
                enable.auto.commit: '0'
            topicConfiguration:
                auto.offset.reset: 'smallest'
            timeout_consuming_queue: 500
            topics:
                - eventUsers
